Traceback (most recent call last):
  File "/home/lperez/main/optimizer-pso/scripts/../main.py", line 69, in <module>
    main()
  File "/home/lperez/main/optimizer-pso/scripts/../main.py", line 60, in main
    trainer = load_trainer(args.trainer,
  File "/home/lperez/main/optimizer-pso/optimzerpso/core/helpers.py", line 22, in load_trainer
    return SupervisedTrainer(model,
TypeError: __init__() got multiple values for argument 'optimizer'
Traceback (most recent call last):
  File "/home/lperez/main/optimizer-pso/scripts/../main.py", line 69, in <module>
    main()
  File "/home/lperez/main/optimizer-pso/scripts/../main.py", line 60, in main
    trainer = load_trainer(args.trainer,
  File "/home/lperez/main/optimizer-pso/optimzerpso/core/helpers.py", line 22, in load_trainer
    return SupervisedTrainer(model,
TypeError: __init__() got multiple values for argument 'optimizer'
